### ISSUE TITLE
Add support to maintain user session between logins.

### ISSUE THREAD

**Issue by ammarahm-ed** [drbuche/InstaBot#6]
Every time I run the bot, it will login again. We cant store the session in bot but we can use Browser Profiles. Attach selenium to a Profile when loading the driver. While tinkering around the code, what I did was remove all the login logic and login to instagram via Firefox browser then provide the profile to selenium and it worked without giving anything and reused the session however for some reason the session is not maintained if I login from selenium and use a profile. But it would a good addition and less creepy I think.

Also have you thought whether Selenium can be detected by instagram Servers etc? The browser shows that it is being controlled, I wonder if the website can also take that info and send it to instagram?

**Comment by drbuche** [comment]
I used the manual login for security reasons because if there is a problem, this prevents automatic logins in an error loop.

Some sites may know that you use selenium, but the bot's steps follow the rules so as not to cause problems.
But if you want, you can take a look at `useragent` selenium or `cdc_`
